import os

path = r'c:\Users\Dinesh\OneDrive\Desktop\PneumoVisionAI\frontend\pages\predict.tsx'

lines = []
lines.append("import React, { useState, useCallback } from 'react';")
lines.append("import { motion } from 'framer-motion';")
lines.append("import { useDropzone } from 'react-dropzone';")
lines.append("import toast from 'react-hot-toast';")
lines.append("")
lines.append("import { useAppDispatch, setUploading, addPrediction } from '@/services/store';")
lines.append("import { predictionAPI } from '@/services/api';")
lines.append("")
lines.append("export default function PredictPage() {")
lines.append("  const dispatch = useAppDispatch();")
lines.append("  const [uploadedFile, setUploadedFile] = useState<File | null>(null);")
lines.append("  const [preview, setPreview] = useState<string | null>(null);")
lines.append("  const [isUploading, setIsUploading] = useState(false);")
lines.append("  const [result, setResult] = useState<any>(null);")
lines.append("  const [error, setError] = useState<string | null>(null);")
lines.append("")
lines.append("  const onDrop = useCallback(async (acceptedFiles: File[]) => {")
lines.append("    const file = acceptedFiles[0];")
lines.append("    if (!file) return;")
lines.append("    const validTypes = ['image/png', 'image/jpeg', 'image/jpg'];")
lines.append("    if (!validTypes.includes(file.type)) {")
lines.append("      toast.error('Please upload a PNG, JPG, or JPEG image');")
lines.append("      return;")
lines.append("    }")
lines.append("    if (file.size > 10 * 1024 * 1024) {")
lines.append("      toast.error('File size must be less than 10MB');")
lines.append("      return;")
lines.append("    }")
lines.append("    setUploadedFile(file);")
lines.append("    setPreview(URL.createObjectURL(file));")
lines.append("    setResult(null);")
lines.append("    setError(null);")
lines.append("    setIsUploading(true);")
lines.append("    dispatch(setUploading(true));")
lines.append("    try {")
lines.append("      const res = await predictionAPI.upload(file);")
lines.append("      setResult(res.data);")
lines.append("      dispatch(addPrediction(res.data));")
lines.append("      toast.success('Analysis complete!');")
lines.append("    } catch (err: any) {")
lines.append("      const message = err.response?.data?.detail || 'Upload failed. Make sure the backend server is running.';")
lines.append("      setError(message);")
lines.append("      toast.error(message);")
lines.append("    } finally {")
lines.append("      setIsUploading(false);")
lines.append("      dispatch(setUploading(false));")
lines.append("    }")
lines.append("  }, [dispatch]);")
lines.append("")
lines.append("  const { getRootProps, getInputProps, isDragActive } = useDropzone({")
lines.append("    onDrop,")
lines.append("    accept: { 'image/*': ['.png', '.jpg', '.jpeg'] },")
lines.append("    maxFiles: 1,")
lines.append("    maxSize: 10 * 1024 * 1024,")
lines.append("  });")
lines.append("")
lines.append("  const handleDownloadReport = async () => {")
lines.append("    if (!result?.id) return;")
lines.append("    try {")
lines.append("      const reportRes = await fetch('http://localhost:8000/reports/' + result.id);")
lines.append("      const blob = await reportRes.blob();")
lines.append("      const url = window.URL.createObjectURL(blob);")
lines.append("      const a = document.createElement('a');")
lines.append("      a.href = url;")
lines.append("      a.download = 'pneumovision_report_' + result.id + '.pdf';")
lines.append("      document.body.appendChild(a);")
lines.append("      a.click();")
lines.append("      window.URL.revokeObjectURL(url);")
lines.append("      document.body.removeChild(a);")
lines.append("      toast.success('Report downloaded');")
lines.append("    } catch (err) {")
lines.append("      toast.error('Download failed');")
lines.append("    }")
lines.append("  };")
lines.append("")
lines.append("  return (")
lines.append('    <div className="max-w-4xl mx-auto space-y-8">')
lines.append('      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>')
lines.append('        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">X-Ray Analysis</h1>')
lines.append('        <p className="text-gray-500 dark:text-gray-400">')
lines.append('          Upload a chest X-ray image for AI-powered pneumonia detection')
lines.append('        </p>')
lines.append('      </motion.div>')
lines.append('')
lines.append('      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>')
lines.append('        <div')
lines.append('          {...getRootProps()}')
lines.append('          className={')
lines.append("            'relative border-2 border-dashed rounded-2xl p-12 text-center cursor-pointer transition-all duration-300 ' +")
lines.append('            (isDragActive')
lines.append("              ? 'border-primary-500 bg-primary-50 dark:bg-primary-900/20'")
lines.append("              : 'border-gray-300 dark:border-gray-600 hover:border-primary-400 hover:bg-gray-50 dark:hover:bg-gray-800/50'")
lines.append('            )')
lines.append('          }')
lines.append('        >')
lines.append('          <input {...getInputProps()} />')
lines.append('          {preview ? (')
lines.append('            <div className="relative">')
lines.append('              <img src={preview} alt="X-Ray Preview" className="max-h-80 mx-auto rounded-xl shadow-lg" />')
lines.append('              {isUploading && (')
lines.append('                <div className="absolute inset-0 bg-black/40 rounded-xl flex items-center justify-center">')
lines.append('                  <div className="text-white text-center">')
lines.append('                    <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-white mx-auto mb-2"></div>')
lines.append('                    <p>Analyzing...</p>')
lines.append('                  </div>')
lines.append('                </div>')
lines.append('              )}')
lines.append('            </div>')
lines.append('          ) : (')
lines.append('            <div>')
lines.append('              <div className="text-6xl mb-4">{isDragActive ? "\uD83D\uDCC2" : "\uD83D\uDCE4"}</div>')
lines.append('              <p className="text-xl font-semibold text-gray-700 dark:text-gray-300 mb-2">')
lines.append('                {isDragActive ? "Drop your X-Ray here" : "Drag and drop chest X-ray"}')
lines.append('              </p>')
lines.append('              <p className="text-gray-500 dark:text-gray-400 mb-4">or click to browse</p>')
lines.append('              <div className="inline-flex items-center gap-2 px-4 py-2 bg-gray-100 dark:bg-gray-700 rounded-lg text-sm text-gray-500 dark:text-gray-400">')
lines.append('                <span>PNG, JPG, JPEG</span>')
lines.append('                <span>|</span>')
lines.append('                <span>Max 10MB</span>')
lines.append('              </div>')
lines.append('            </div>')
lines.append('          )}')
lines.append('        </div>')
lines.append('      </motion.div>')
lines.append('')
lines.append('      {isUploading && !result && (')
lines.append('        <div className="text-center">')
lines.append('          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-500 mx-auto"></div>')
lines.append('          <p className="text-gray-500 mt-2">Analyzing your X-ray...</p>')
lines.append('        </div>')
lines.append('      )}')
lines.append('')
lines.append('      {result && (')
lines.append('        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">')
lines.append('          <div')
lines.append('            className={')
lines.append("              'card text-center ' +")
lines.append("              (result.prediction === 'Normal'")
lines.append("                ? 'border-green-200 dark:border-green-800'")
lines.append("                : 'border-red-200 dark:border-red-800'")
lines.append('              )')
lines.append('            }')
lines.append('          >')
lines.append('            <div className="text-5xl mb-4">{result.prediction === "Normal" ? "\u2705" : "\u26A0\uFE0F"}</div>')
lines.append('            <h2')
lines.append('              className={')
lines.append("                'text-3xl font-bold mb-2 ' +")
lines.append("                (result.prediction === 'Normal' ? 'text-success' : 'text-danger')")
lines.append('              }')
lines.append('            >')
lines.append('              {result.prediction}')
lines.append('            </h2>')
lines.append('            <p className="text-gray-500 dark:text-gray-400 mb-6">')
lines.append('              Detected with {(result.confidence * 100).toFixed(1)}% confidence')
lines.append('            </p>')
lines.append('            <div className="max-w-md mx-auto space-y-4">')
lines.append('              <div>')
lines.append('                <div className="flex justify-between text-sm mb-1">')
lines.append('                  <span className="text-gray-600 dark:text-gray-400">Normal</span>')
lines.append('                  <span className="font-semibold">{(result.probability_normal * 100).toFixed(1)}%</span>')
lines.append('                </div>')
lines.append('                <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-3">')
lines.append('                  <div')
lines.append('                    className="bg-success rounded-full h-3 transition-all duration-1000"')
lines.append("                    style={{ width: result.probability_normal * 100 + '%' }}")
lines.append('                  ></div>')
lines.append('                </div>')
lines.append('              </div>')
lines.append('              <div>')
lines.append('                <div className="flex justify-between text-sm mb-1">')
lines.append('                  <span className="text-gray-600 dark:text-gray-400">Pneumonia</span>')
lines.append('                  <span className="font-semibold">{(result.probability_pneumonia * 100).toFixed(1)}%</span>')
lines.append('                </div>')
lines.append('                <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-3">')
lines.append('                  <div')
lines.append('                    className="bg-danger rounded-full h-3 transition-all duration-1000"')
lines.append("                    style={{ width: result.probability_pneumonia * 100 + '%' }}")
lines.append('                  ></div>')
lines.append('                </div>')
lines.append('              </div>')
lines.append('            </div>')
lines.append('          </div>')
lines.append('')
lines.append('          {result.gradcam_image && (')
lines.append('            <div className="card">')
lines.append('              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4">AI Attention Map (Grad-CAM)</h3>')
lines.append('              <div className="flex justify-center">')
lines.append('                <img')
lines.append("                  src={'http://localhost:8000/' + result.gradcam_image.replace(/\\\\/g, '/')}")
lines.append('                  alt="GradCAM Heatmap"')
lines.append('                  className="max-h-80 rounded-xl shadow-lg"')
lines.append('                />')
lines.append('              </div>')
lines.append('              <p className="text-center text-sm text-gray-500 mt-3">')
lines.append('                Red regions indicate areas the AI focused on for its decision')
lines.append('              </p>')
lines.append('            </div>')
lines.append('          )}')
lines.append('')
lines.append('          <div className="flex justify-center gap-4">')
lines.append('            <button onClick={handleDownloadReport} className="btn-primary">')
lines.append('              Download Report')
lines.append('            </button>')
lines.append('            <button')
lines.append('              onClick={() => {')
lines.append('                setResult(null);')
lines.append('                setPreview(null);')
lines.append('                setUploadedFile(null);')
lines.append('              }}')
lines.append('              className="btn-secondary"')
lines.append('            >')
lines.append('              New Analysis')
lines.append('            </button>')
lines.append('          </div>')
lines.append('        </motion.div>')
lines.append('      )}')
lines.append('')
lines.append('      {error && (')
lines.append('        <motion.div')
lines.append('          initial={{ opacity: 0 }}')
lines.append('          animate={{ opacity: 1 }}')
lines.append('          className="card bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800"')
lines.append('        >')
lines.append('          <p className="text-red-600 dark:text-red-400">{error}</p>')
lines.append('        </motion.div>')
lines.append('      )}')
lines.append('    </div>')
lines.append('  );')
lines.append('}')
lines.append('')

content = '\n'.join(lines)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print('File written successfully!')
print(f'Total lines: {len(lines)}')
</｜｜DSML｜｜parameter>
</create_file>
